[package]
name = "cargo-deploy"
version = "0.1.0"
edition = "2024"
rust-version = "1.90.0"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
cargo_metadata = "0.23.1"
clap = { version = "4.5.59", features = ["derive"] }
